package com.rahul.appmanager;

import java.util.HashMap;

/**
 * Created by Rahul on 30 Apr 2016.
 */
public class Constants {
    public static final HashMap<String , String> permissionDescription;
    static {
        permissionDescription = new HashMap<>();
        permissionDescription.put("ACCESS_CHECKIN_PROPERTIES","Allows read/write access to the \"properties\" table in the checkin database, to change values that get uploaded.");
        permissionDescription.put("ACCESS_COARSE_LOCATION","Allows an app to access approximate location.");
        permissionDescription.put("ACCESS_FINE_LOCATION","Allows an app to access precise location.");
        permissionDescription.put("ACCESS_LOCATION_EXTRA_COMMANDS","Allows an application to access extra location provider commands.");
        permissionDescription.put("ACCESS_NETWORK_STATE","Allows applications to access information about networks.");
        permissionDescription.put("ACCESS_NOTIFICATION_POLICY", "Marker permission for applications that wish to access notification policy.");
        permissionDescription.put("ACCESS_WIFI_STATE","Allows applications to access information about Wi-Fi networks.");
        permissionDescription.put("ACCOUNT_MANAGER","Allows applications to call into AccountAuthenticators.");
        permissionDescription.put("ADD_VOICEMAIL","Allows an application to add voicemails into the system.");
        permissionDescription.put("BATTERY_STATS","Allows an application to collect battery statistics");
        permissionDescription.put("BIND_ACCESSIBILITY_SERVICE","Must be required by an AccessibilityService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_APPWIDGET","Allows an application to tell the AppWidget service which application can access AppWidget's data.");
        permissionDescription.put("BIND_CARRIER_MESSAGING_SERVICE", "This constant was deprecated in API level 23. Use BIND_CARRIER_SERVICES instead");
        permissionDescription.put("BIND_CARRIER_SERVICES", "The system process that is allowed to bind to services in carrier apps will have this permission.");
        permissionDescription.put("BIND_CHOOSER_TARGET_SERVICE", "Must be required by a ChooserTargetService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_DEVICE_ADMIN","Must be required by device administration receiver, to ensure that only the system can interact with it.");
        permissionDescription.put("BIND_DREAM_SERVICE","Must be required by an DreamService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_INCALL_SERVICE","Must be required by a InCallService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_INPUT_METHOD","Must be required by an InputMethodService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_MIDI_DEVICE_SERVICE","Must be required by an MidiDeviceService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_NFC_SERVICE","Must be required by a HostApduService or OffHostApduService to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_NOTIFICATION_LISTENER_SERVICE","Must be required by an NotificationListenerService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_PRINT_SERVICE","Must be required by a PrintService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_REMOTEVIEWS","Must be required by a RemoteViewsService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_TELECOM_CONNECTION_SERVICE", "Must be required by a ConnectionService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_TEXT_SERVICE","Must be required by a TextService (eg SpellCheckerService) to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_TV_INPUT","Must be required by a TvInputService to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_VOICE_INTERACTION","Must be required by a VoiceInteractionService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_VPN_SERVICE","Must be required by a VpnService, to ensure that only the system can bind to it.");
        permissionDescription.put("BIND_WALLPAPER","Must be required by a WallpaperService, to ensure that only the system can bind to it.");
        permissionDescription.put("BLUETOOTH","Allows applications to connect to paired bluetooth devices.");
        permissionDescription.put("BLUETOOTH_ADMIN","Allows applications to discover and pair bluetooth devices.");
        permissionDescription.put("BLUETOOTH_PRIVILEGED","Allows applications to pair bluetooth devices without user interaction, and to allow or disallow phonebook access or message access.");
        permissionDescription.put("BODY_SENSORS","Allows an application to access data from sensors that the user uses to measure what is happening inside his/her body, such \"as heart rate.");
        permissionDescription.put("BROADCAST_PACKAGE_REMOVED","Allows an application to broadcast a notification that an application package has been removed.");
        permissionDescription.put("BROADCAST_SMS","Allows an application to broadcast an SMS receipt notification.");
        permissionDescription.put("BROADCAST_STICKY","Allows an application to broadcast sticky intents.");
        permissionDescription.put("BROADCAST_WAP_PUSH","Allows an application to broadcast a WAP PUSH receipt notification.");
        permissionDescription.put("CALL_PHONE","Allows an application to initiate a phone call without going through the Dialer user interface for the user to confirm the call.");
        permissionDescription.put("CALL_PRIVILEGED","Allows an application to call any phone number, including emergency numbers, without going through the Dialer user interface for the user to confirm the call being placed.");
        permissionDescription.put("CAMERA", "Required to be able to access the camera device.");
        permissionDescription.put("CAPTURE_AUDIO_OUTPUT","Allows an application to capture audio output.");
        permissionDescription.put("CAPTURE_SECURE_VIDEO_OUTPUT","Allows an application to capture secure video output.");
        permissionDescription.put("CAPTURE_VIDEO_OUTPUT","Allows an application to capture video output.");
        permissionDescription.put("CHANGE_COMPONENT_ENABLED_STATE","Allows an application to change whether an application component (other than its own) is enabled or not.");
        permissionDescription.put("CHANGE_CONFIGURATION","Allows an application to modify the current configuration, such as locale.");
        permissionDescription.put("CHANGE_NETWORK_STATE","Allows applications to change network connectivity state.");
        permissionDescription.put("CHANGE_WIFI_MULTICAST_STATE","Allows applications to enter Wi-Fi Multicast mode.");
        permissionDescription.put("CHANGE_WIFI_STATE","Allows applications to change Wi-Fi connectivity state.");
        permissionDescription.put("CLEAR_APP_CACHE","Allows an application to clear the caches of all installed applications on the device.");
        permissionDescription.put("CONTROL_LOCATION_UPDATES","Allows enabling/disabling location update notifications from the radio.");
        permissionDescription.put("DELETE_CACHE_FILES","Allows an application to delete cache files.");
        permissionDescription.put("DELETE_PACKAGES","Allows an application to delete packages.");
        permissionDescription.put("DIAGNOSTIC","Allows applications to RW to diagnostic resources.");
        permissionDescription.put("DISABLE_KEYGUARD","Allows applications to disable the keyguard if it is not secure.");
        permissionDescription.put("DUMP","Allows an application to retrieve state dump information from system services.");
        permissionDescription.put("EXPAND_STATUS_BAR","Allows an application to expand or collapse the status bar.");
        permissionDescription.put("FACTORY_TEST",   "Run as a manufacturer test application, running as the root user.");
        permissionDescription.put("FLASHLIGHT","Allows access to the flashlight.");
        permissionDescription.put("GET_ACCOUNTS","Allows access to the list of accounts in the Accounts Service.");
        permissionDescription.put("GET_ACCOUNTS_PRIVILEGED","Allows access to the list of accounts in the Accounts Service.");
        permissionDescription.put("GET_PACKAGE_SIZE","Allows an application to find out the space used by any package.");
        permissionDescription.put("GET_TASKS",  "This constant was deprecated in API level 21. No longer enforced.");
        permissionDescription.put("GLOBAL_SEARCH",  "This permission can be used on content providers to allow the global search system to access their data.");
        permissionDescription.put("INSTALL_LOCATION_PROVIDER","Allows an application to install a location provider into the Location Manager.");
        permissionDescription.put("INSTALL_PACKAGES","Allows an application to install packages.");
        permissionDescription.put("INSTALL_SHORTCUT","Allows an application to install a shortcut in Launcher.");
        permissionDescription.put("INTERNET","Allows applications to open network sockets.");
        permissionDescription.put("KILL_BACKGROUND_PROCESSES","Allows an application to call killBackgroundProcesses(String).");
        permissionDescription.put("LOCATION_HARDWARE","Allows an application to use location features in hardware, such as the geofencing api.");
        permissionDescription.put("MANAGE_DOCUMENTS","Allows an application to manage access to documents, usually as part of a document picker.");
        permissionDescription.put("MASTER_CLEAR",   ",Not for use by third-party applications.");
        permissionDescription.put("MEDIA_CONTENT_CONTROL","Allows an application to know what content is playing and control its playback.");
        permissionDescription.put("MODIFY_AUDIO_SETTINGS","Allows an application to modify global audio settings.");
        permissionDescription.put("MODIFY_PHONE_STATE","Allows modification of the telephony state - power on, mmi, etc.");
        permissionDescription.put("MOUNT_FORMAT_FILESYSTEMS","Allows formatting file systems for removable storage.");
        permissionDescription.put("MOUNT_UNMOUNT_FILESYSTEMS","Allows mounting and unmounting file systems for removable storage.");
        permissionDescription.put("NFC","Allows applications to perform I/O operations over NFC.");
        permissionDescription.put("PACKAGE_USAGE_STATS","Allows an application to collect component usage statistics");
        permissionDescription.put("PROCESS_OUTGOING_CALLS","Allows an application to see the number being dialed during an outgoing call with the option to redirect the call to a different number or abort the call altogether.");
        permissionDescription.put("READ_CALENDAR","Allows an application to read the user's calendar data.");
        permissionDescription.put("READ_CALL_LOG","Allows an application to read the user's call log.");
        permissionDescription.put("READ_CONTACTS","Allows an application to read the user's contacts data.");
        permissionDescription.put("READ_EXTERNAL_STORAGE","Allows an application to read from external storage.");
        permissionDescription.put("READ_FRAME_BUFFER","Allows an application to take screen shots and more generally get access to the frame buffer data.");
        permissionDescription.put("READ_INPUT_STATE",   "This constant was deprecated in API level 16. The API that used this permission has been removed.");
        permissionDescription.put("READ_LOGS","Allows an application to read the low-level system log files.");
        permissionDescription.put("READ_PHONE_STATE","Allows read only access to phone state.");
        permissionDescription.put("READ_SMS","Allows an application to read SMS messages.");
        permissionDescription.put("READ_SYNC_SETTINGS","Allows applications to read the sync settings.");
        permissionDescription.put("READ_SYNC_STATS","Allows applications to read the sync stats.");
        permissionDescription.put("READ_VOICEMAIL","Allows an application to read voicemails in the system.");
        permissionDescription.put("REBOOT", "Required to be able to reboot the device.");
        permissionDescription.put("RECEIVE_BOOT_COMPLETED","Allows an application to receive the ACTION_BOOT_COMPLETED that is broadcast after the system finishes booting.");
        permissionDescription.put("RECEIVE_MMS","Allows an application to monitor incoming MMS messages.");
        permissionDescription.put("RECEIVE_SMS","Allows an application to receive SMS messages.");
        permissionDescription.put("RECEIVE_WAP_PUSH","Allows an application to receive WAP push messages.");
        permissionDescription.put("RECORD_AUDIO","Allows an application to record audio.");
        permissionDescription.put("REORDER_TASKS","Allows an application to change the Z-order of tasks.");
        permissionDescription.put("REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",   "Permission an application must hold in order to use ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS.");
        permissionDescription.put("REQUEST_INSTALL_PACKAGES","Allows an application to request installing packages.");
        permissionDescription.put("RESTART_PACKAGES",   "This constant was deprecated in API level 8. The restartPackage(String) API is no longer supported.");
        permissionDescription.put("SEND_RESPOND_VIA_MESSAGE","Allows an application (Phone) to send a request to other applications to handle the respond-via-message action during incoming calls.");
        permissionDescription.put("SEND_SMS","Allows an application to send SMS messages.");
        permissionDescription.put("SET_ALARM","Allows an application to broadcast an Intent to set an alarm for the user.");
        permissionDescription.put("SET_ALWAYS_FINISH","Allows an application to control whether activities are immediately finished when put in the background.");
        permissionDescription.put("SET_ANIMATION_SCALE", "Modify the global animation scaling factor.");
        permissionDescription.put("SET_DEBUG_APP",  "Configure an application for debugging.");
        permissionDescription.put("SET_PREFERRED_APPLICATIONS", "This constant was deprecated in API level 7. No longer useful, see addPackageToPreferred(String) for details.");
        permissionDescription.put("SET_PROCESS_LIMIT","Allows an application to set the maximum number of (not needed) application processes that can be running.");
        permissionDescription.put("SET_TIME","Allows applications to set the system time.");
        permissionDescription.put("SET_TIME_ZONE","Allows applications to set the system time zone.");
        permissionDescription.put("SET_WALLPAPER","Allows applications to set the wallpaper.");
        permissionDescription.put("SET_WALLPAPER_HINTS","Allows applications to set the wallpaper hints.");
        permissionDescription.put("SIGNAL_PERSISTENT_PROCESSES","Allow an application to request that a signal be sent to all persistent processes.");
        permissionDescription.put("STATUS_BAR","Allows an application to open, close, or disable the status bar and its icons.");
        permissionDescription.put("SYSTEM_ALERT_WINDOW","Allows an app to create windows using the type TYPE_SYSTEM_ALERT, shown on top of all other apps.");
        permissionDescription.put("TRANSMIT_IR","Allows using the device's IR transmitter, if available.");
        permissionDescription.put("UNINSTALL_SHORTCUT","Allows an application to uninstall a shortcut in Launcher.");
        permissionDescription.put("UPDATE_DEVICE_STATS","Allows an application to update device statistics.");
        permissionDescription.put("USE_FINGERPRINT","Allows an app to use fingerprint hardware.");
        permissionDescription.put("USE_SIP","Allows an application to use SIP service.");
        permissionDescription.put("VIBRATE","Allows access to the vibrator.");
        permissionDescription.put("WAKE_LOCK","Allows using PowerManager WakeLocks to keep processor from sleeping or screen from dimming.");
        permissionDescription.put("WRITE_APN_SETTINGS","Allows applications to write the apn settings.");
        permissionDescription.put("WRITE_CALENDAR","Allows an application to write the user's calendar data.");
        permissionDescription.put("WRITE_CALL_LOG","Allows an application to write (but not read) the user's contacts data.");
        permissionDescription.put("WRITE_CONTACTS","Allows an application to write the user's contacts data.");
        permissionDescription.put("WRITE_EXTERNAL_STORAGE","Allows an application to write to external storage.");
        permissionDescription.put("WRITE_GSERVICES","Allows an application to modify the Google service map.");
        permissionDescription.put("WRITE_SECURE_SETTINGS","Allows an application to read or write the secure system settings.");
        permissionDescription.put("WRITE_SETTINGS","Allows an application to read or write the system settings.");
        permissionDescription.put("WRITE_SYNC_SETTINGS","Allows applications to write the sync settings.");
        permissionDescription.put("WRITE_VOICEMAIL","Allows an application to modify and remove existing voicemails in the system.");
    }
}
